#!/bin/tcsh

    ### LSF syntax
    #BSUB -nnodes 1                   #number of nodes
    #BSUB -W 2 #walltime in minutes
    #BSUB -e myerrors.txt             #stderr
    #BSUB -o myoutput.txt             #stdout
    #BSUB -J dk-simple #name of job
    #BSUB -q pbatch                   #queue to use

    ### Shell scripting
    date; hostname
    echo -n 'JobID is '; echo $LSB_JOBID
    cd /p/gscratch1/kruse11/project
    cp ~/inputs/run2048.inp .

    ### Launch parallel executable

    ### Start the server, build the input file
    sdskv-server-daemon -f serveraddr.txt na+sm foo
    cat serveraddr.txt > input.txt
    cat otherargs.txt >> input.txt

    ### preload the pmpi shared file, run the main program
    LD_PRELOAD=./pmpi-lib.so
    lrun -N 2 ./main-generate $(<input.txt)
    echo 'Done'
